### ISSUE TITLE
Feature Request: Large Icons

### ISSUE THREAD

**Issue by Hasan-01** [hdlx/AltAppSwitcher#15]
I feel the current icons are too small. If it's meant to be like the Mac app switcher, the icons should be a bit larger. Or maybe a option to change the icon size would be cool, too.

btw, thank you for making this! I've been looking for something like this for a while. While I'm currently unable to support the project, if I continue using it in the future, I'll definitely donate. Best of luck, buddy! ❤️

**Comment by crispearson** [comment]
+1 for this. 

Thanks for making it!

**Comment by hdlx** [comment]
Thanks for the feedback! This is a good idea, I'll add a size option 🙂

**Comment by hdlx** [comment]
This should be in the last update. The default size is 1.5 times Windows default icon size. A "scale" option lets you tweak it from the config file.
Some icons still lack definition. It is not trivial to get high res. icons for some apps, but I will try to improve this.

**Comment by Hasan-01** [comment]
Thank you! ❤️  
This is great, exactly what I was looking for. Love that it auto-resizes when there are too many apps.
