### ISSUE TITLE
Request: alt-tilde act like command-tilde

### ISSUE THREAD

**Issue by crispearson** [hdlx/AltAppSwitcher#16]
On Mac, pressing command-tilde after pressing command-tab while still holding command, cycles the selection in the opposite direction. I'd love this functionality in AltAppSwitcher. I tried adjusting the config.txt but didn't get it to work in this way. Possibly doing something wrong.

**Comment by hdlx** [comment]
I did not know about this behavior, your not doing it wrong, it can't indeed be achieved with the current "invert order" key implementation (left shift by default). I'll check on Mac and try to add something like this, maybe trough an option.
Thanks for the feedback!

**Comment by crispearson** [comment]
Thanks, that would be great! 

Another aspect of how the Mac switcher works: pressing escape closes the switcher and doesn't switch or close any windows or apps.

**Comment by hdlx** [comment]
Should be good in the last update.

**Comment by crispearson** [comment]
> It should be good in the last update 🙂

Thank you so much!
