### ISSUE TITLE
Latest release contains Trojan:Script/Wacatac.B!ml according to windows security

### ISSUE THREAD

**Issue by crispearson** [hdlx/AltAppSwitcher#18]
Latest release contains Trojan:Script/Wacatac.B!ml according to windows security

Didn't have this issue with prior release

**Comment by hdlx** [comment]
Hello, thanks for the feedback 🙂 This issue is known already. Pleaase see https://github.com/hdlx/AltAppSwitcher/issues/8
Unfortunately, I believe there is not much I can do. "...!ml" stands for machine learning detection and it's hard to know what makes it detected as Trojan.

**Comment by Hasan-01** [comment]
Oh! Maybe this is why sometimes the app suddenly closes! And a lot of the time, it doesn't run at startup!

I was about to report it as a bug.

**Comment by crispearson** [comment]
> Hello, thanks for the feedback 🙂 This issue is already known (#8) Unfortunately, I believe there is not much I can do. "...!ml" stands for machine learning detection and it's hard to know what makes it detected as Trojan.

Thanks for responding, and sorry for not noticing this was a dupe
