### ISSUE TITLE
Feature Suggestion: Turn off the select on hover 

### ISSUE THREAD

**Issue by Hasan-01** [hdlx/AltAppSwitcher#19]
![Arc_uWjmDozKX2](https://github.com/user-attachments/assets/24dc1c6a-0c41-4b15-addd-bebce1cb8fcf)

This select-on-hover feature is kind of problematic. Normally, when you press Alt + Tab once, it switches to the most recent app, but if the mouse hovers over the popup, it selects whichever app it lands on. It’s not a huge issue, but it can get annoying since most of us are used to the default Alt-Tab behavior in Windows.

It would be a quality of life improvement if we could turn off the select-on-hover feature. I don’t think anyone would mind using an extra click to open an app that’s further away.

**Comment by hdlx** [comment]
Hey, indeed this should behave as you describe,  Click to apply mouse selection, release to apply keyboard selection. I'll fix this and probably a separated selection indicator just for the mouse, like windows does (a soft background color change).

**Comment by hdlx** [comment]
Should be good in the last version

**Comment by Hasan-01** [comment]
Yay! It works like a charm. Thanks man! I really appreciate it ❤️
