### ISSUE TITLE
Circling feature above the apps

### ISSUE THREAD

**Issue by wisuzaje** [hdlx/AltAppSwitcher#24]
![SybGFvszfT](https://github.com/user-attachments/assets/533c74fd-446c-4cf4-b136-c7b3a4a8c105)

https://github.com/user-attachments/assets/9f831e8b-7600-4361-93bf-e171f0a1df0c

I am having a problem with this "circling feature" above the apps whenever I use my mouse to select an app like so...what could be the issue?

**Comment by hdlx** [comment]
Hey, thanks for the feedback. This is something I noticed too. Please retry last version, it should be better 🙂 I just updated the archive with a fix (I updated the archive without releasing a new version since this is minor)

**Comment by wisuzaje** [comment]
Thank you so much! that has fixed it.
